# Generated by Django 4.0 on 2022-01-02 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tffsite', '0002_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
