# Generated by Django 4.0 on 2022-01-02 09:04

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='upload',
            field=models.ImageField(default=1, upload_to=events.models.user_directory_path),
            preserve_default=False,
        ),
    ]
