# Generated by Django 4.0 on 2022-01-02 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('events', '0004_alter_player_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('rating', models.IntegerField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='reviews',
            field=models.ManyToManyField(related_name='user_reviews', to='events.PlayerReview'),
        ),
    ]
