# Generated by Django 4.0 on 2022-01-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_playerreview_player_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='user_reviews', to='events.PlayerReview'),
        ),
    ]
