# Generated by Django 4.0 on 2022-01-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_player_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerreview',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
