# Generated by Django 4.0 on 2022-01-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
