# Generated by Django 4.0 on 2022-01-02 12:27

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_player_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img',
            field=models.ImageField(default=1, upload_to=events.models.unique_upload_events),
            preserve_default=False,
        ),
    ]
