# Generated by Django 4.0 on 2022-01-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Competition_Level',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='Competition_style',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
