# Generated by Django 4.0 on 2022-01-06 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_location_event_eventlocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='lng',
            new_name='longitude',
        ),
    ]
