# Generated by Django 4.0 on 2022-01-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_rename_lat_location_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eventLocation',
            new_name='event_Location',
        ),
        migrations.AddField(
            model_name='location',
            name='location_Title',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.CharField(max_length=15),
        ),
    ]
