# Generated by Django 4.0 on 2022-01-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_rename_eventlocation_event_event_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_Title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.IntegerField(max_length=15),
        ),
    ]
