# Generated by Django 4.0 on 2022-01-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_location_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(max_length=15),
        ),
    ]
