# Generated by Django 4.0 on 2022-01-14 07:00

import autoslug.fields
from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('news_type', models.CharField(max_length=50)),
                ('news_discription', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=50)),
                ('img', models.ImageField(upload_to=events.models.unique_upload_events)),
                ('date', models.DateField(blank=True)),
                ('time', models.TimeField(blank=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
