# Generated by Django 4.0 on 2022-01-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='content',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='new',
            name='news_discription',
            field=models.CharField(max_length=500),
        ),
    ]
