# Generated by Django 4.0 on 2022-01-14 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_alter_new_content_alter_new_news_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='date_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
