# Generated by Django 4.0 on 2022-01-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_remove_new_date_remove_new_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
