# Generated by Django 4.0 on 2022-01-14 10:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_alter_new_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
