# Generated by Django 4.0 on 2022-01-14 15:06

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_alter_new_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='review_page_img',
            field=models.ImageField(default=1, upload_to=events.models.unique_upload),
            preserve_default=False,
        ),
    ]
