# Generated by Django 4.0 on 2022-02-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_alter_player_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enent_name', models.CharField(max_length=100)),
                ('event_organizer', models.CharField(max_length=100)),
                ('event_date', models.DateField(blank=True)),
            ],
        ),
    ]
