# Generated by Django 4.0 on 2022-02-19 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='competition_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='event_style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='event_address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='event_cost',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='event_rules_requlations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='events',
            name='event_social_links_fb',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='event_social_links_tw',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='event_website',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='organizer_contact_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='organizer_contact_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='organizer_social_links_fb',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='organizer_social_links_tw',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='special_request_form_event_organizer',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='competition_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.competition_type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='event_style',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.event_style'),
            preserve_default=False,
        ),
    ]
