# Generated by Django 4.0 on 2022-02-19 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_competition_type_event_style_events_event_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='competition_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.competition_type'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_cost',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_social_links_fb',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_social_links_tw',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event_style'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_website',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='events',
            name='organizer_contact_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='events',
            name='organizer_social_links_fb',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='events',
            name='organizer_social_links_tw',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='events',
            name='special_request_form_event_organizer',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
