# Generated by Django 4.0 on 2022-01-02 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=5)),
                ('weight', models.CharField(max_length=5)),
                ('Competition_style', models.CharField(max_length=50)),
                ('Competition_Level', models.CharField(max_length=50)),
                ('profile_img', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_name', to='auth.user')),
            ],
        ),
    ]
