# Generated by Django 4.0 on 2022-01-02 11:05

import UserInformation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInformation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='profile_img',
            field=models.ImageField(upload_to=UserInformation.models.unique_upload),
        ),
    ]
