# Generated by Django 4.0 on 2022-02-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInformation', '0003_usertype_userinformation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='a',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
