# Generated by Django 4.0 on 2022-02-19 07:39

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('age', models.CharField(max_length=5)),
                ('weight', models.CharField(max_length=5)),
                ('Competition_style', models.CharField(max_length=50)),
                ('Competition_Level', models.CharField(max_length=50)),
                ('about', models.TextField(blank=True)),
                ('specification', models.TextField(blank=True)),
            ],
        ),
    ]
