# Generated by Django 4.0 on 2022-03-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='seminar_organizer',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
